server:
  port: 8090
  servlet:
    context-path: /businesscard
  ssl:
    key-store: classpath:ecard.wzpm.com.cn.pfx
    key-store-password: pb1qjvuk
    key-store-type: PKCS12

spring:
  profiles:
      active: dev
  application:
    name: businesscard
  session:
    redis:
      repository-type: default
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/businesscard?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: ecard
    password: ecard@321
    druid:
      max-active: 8
      initial-size: 8
      max-wait: 30000
      min-idle: 8
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      connect-timeout: 30000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 8
  file:
    upload:
      path: D:/upload
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true  #开启驼峰命名转换

